""" Create a program that will play the “cows and bulls” game with the user. The game works like this:
Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, 
tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over.
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.
Say the number generated by the computer is 1038. An example interaction could look like this:
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls"""


import random
import string
import sys

def cows_bulls():
    num = ''.join([random.choice(string.digits) for i in range(4)])
    num = list(num)
    #print(num)
    cows = 0
    bulls = 0
    guess=0
    attempt =0
    while(num != guess):
        guess = input("guess the number: ")
        if(len(guess) == 4):
            guess = list(guess)
        else:
            print("Invalid. Please enter a four digit number: ")
            continue
            
        for i in range(4):
            if num[i] == guess[i]:
                cows = cows + 1
            elif num[i] in guess and num[i] != guess[i]:
                bulls = bulls + 1
        attempt = attempt + 1
        print(cows,"cows")
        print(bulls,"bulls")
    print("number of valid attempts are: ",attempt)
            
if __name__ == "__main__":
    cows_bulls()
